version: '3'


services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot_app
    env_file:
      - '.env'
    # volumes:
    #   - app-data:app
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis_bot_app
    restart: unless-stopped
    hostname: ${REDIS_HOST_NAME}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DATABASES=${REDIS_DATABASES}
    ports:
    - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis-data:/local_storage
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    



volumes:
  app-data:
  redis-data:
    driver: local
    driver_opts:
      type: none
      device: ./local_storage
      o: bind
  
